// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBu6oLQrqVnSv-dyNpEaZQtQN3KkITfU',
    appId: '1:435689705391:web:e217193c693014a705e95a',
    messagingSenderId: '435689705391',
    projectId: 'chat-app-9bca8',
    authDomain: 'chat-app-9bca8.firebaseapp.com',
    storageBucket: 'chat-app-9bca8.firebasestorage.app',
    measurementId: 'G-8PG00YT35W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wrHIuup4lATp-N4Bt_LJlMXTMQx3sb0',
    appId: '1:435689705391:android:c42cd2b028e701a805e95a',
    messagingSenderId: '435689705391',
    projectId: 'chat-app-9bca8',
    storageBucket: 'chat-app-9bca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzd347-UpoMStGcC7kE_5SBWlkNgynUx4',
    appId: '1:435689705391:ios:bcc4d38de9ffd00205e95a',
    messagingSenderId: '435689705391',
    projectId: 'chat-app-9bca8',
    storageBucket: 'chat-app-9bca8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzd347-UpoMStGcC7kE_5SBWlkNgynUx4',
    appId: '1:435689705391:ios:bcc4d38de9ffd00205e95a',
    messagingSenderId: '435689705391',
    projectId: 'chat-app-9bca8',
    storageBucket: 'chat-app-9bca8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBu6oLQrqVnSv-dyNpEaZQtQN3KkITfU',
    appId: '1:435689705391:web:02167df71c60f74005e95a',
    messagingSenderId: '435689705391',
    projectId: 'chat-app-9bca8',
    authDomain: 'chat-app-9bca8.firebaseapp.com',
    storageBucket: 'chat-app-9bca8.firebasestorage.app',
    measurementId: 'G-K8095QDD70',
  );
}
